ANSIBLE_DIR = $(VAR_DIR)/ansible

ANSIBLE_GIT_COMMAND = git -C $(ANSIBLE_DIR)
ANSIBLE_LAST_BUILD = $(ANSIBLE_DIR)/.ansible-last-build
ANSIBLE_REPO = git://github.com/ansible/ansible
ANSIBLE_TAG_PREFIX = v
ANSIBLE_TAG_SUFFIX =
ANSIBLE_VAR_MK = $(MAKEFILE_VAR_DIR)/ansible.mk
ANSIBLE_VERSION = latest

ifeq ($(ANSIBLE_VERSION), latest)
    ANSIBLE_GIT_TAG = origin/HEAD
else
    ANSIBLE_GIT_TAG = $(ANSIBLE_TAG_PREFIX)$(ANSIBLE_VERSION)$(ANSIBLE_TAG_SUFFIX)
endif
