BIN_DIR = bin
CONFIG_DIR = config
DATA_DIR = data
ETC_DIR = etc
VAR_DIR = var

ALL_TARGETS += build
BUILD_TARGETS += initialize
CLEAN_TARGETS +=
DISTCLEAN_TARGETS += clean
INITIALIZE_TARGETS += install
INSTALL_TARGETS +=
