HOMEBREW_DIR = $(VAR_DIR)/homebrew

HOMEBREW_GIT_COMMAND = git -C $(HOMEBREW_DIR)
HOMEBREW_LAST_BUILD = $(HOMEBREW_DIR)/.homebrew-last-build
HOMEBREW_REPO = git://github.com/Homebrew/homebrew.git
HOMEBREW_TAG_PREFIX =
HOMEBREW_TAG_SUFFIX =
HOMEBREW_VAR_MK = $(MAKEFILE_VAR_DIR)/homebrew.mk
HOMEBREW_VERSION = latest

ifeq ($(HOMEBREW_VERSION), latest)
    HOMEBREW_GIT_TAG = origin/HEAD
else
    HOMEBREW_GIT_TAG = $(HOMEBREW_TAG_PREFIX)$(HOMEBREW_VERSION)$(HOMEBREW_TAG_SUFFIX)
endif
