ROSWELL_DIR = $(VAR_DIR)/roswell
ROSWELL_DOT_DIR = $(HOME)/.roswell

ROSWELL_GIT_COMMAND = git --git-dir=$(ROSWELL_DIR)/.git --work-tree=$(ROSWELL_DIR)
ROSWELL_LAST_BUILD = $(ROSWELL_DIR)/.roswel-last-build
ROSWELL_REPO = git://github.com/snmsts/roswell.git
ROSWELL_TAG_PREFIX =
ROSWELL_TAG_SUFFIX =
ROSWELL_VAR_MK = $(MAKEFILE_VAR_DIR)/roswell.mk
ROSWELL_VERSION = latest

ifeq ($(ROSWELL_VERSION), latest)
    ROSWELL_GIT_TAG = origin/HEAD
else
    ROSWELL_GIT_TAG = $(ROSWELL_TAG_PREFIX)$(ROSWELL_VERSION)$(ROSWELL_TAG_SUFFIX)
endif
