" basic
:set autoread
:set wildmode=longest,list

" color
:syntax enable
:set background=dark
:colorscheme koehler

" editor
:set enc=utf-8
:set fenc=utf-8
:set fencs=utf-8,iso-2022-jp,euc-jp,cp932
":set binary noeol

" map
:nnoremap <C-a>         <Home>
:nnoremap <C-d>         <Del>
:nnoremap <C-e>         <End>
:nnoremap <C-l>         <Right>
:nnoremap <C-j>         :bn<ENTER>
:nnoremap <C-k>         :bp<ENTER>
:nnoremap <C-w>         :bd<ENTER>

